name: Build & Test

on:
  pull_request:
    branches:
      - develop
      - qa
      - main
  workflow_dispatch:     

jobs:
  trigger-net-actions:
    uses: EstudioGallo/net-actions/.github/workflows/main.yml@main
    secrets:
      NUGET_USER: ${{ secrets.NUGET_USER }}
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
